#
# SERVER
#
server:
    port: 5402
debug: false

#
# SPRING
#
spring:
    application:
        name: template-springboot-mvc-4x
    quartz:
        auto-startup: false
    servlet:
        multipart:
            max-request-size: 32MB # total request size
            max-file-size: 16MB    # each file size
    main:
        banner-mode: off
    threads:
        virtual:
            enabled: true
    jpa:
        open-in-view: false
    autoconfigure:
        exclude:
            - org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
            
    ## (SBADMIN)
    boot:
        admin:
            client:
                instance:
                    name: template-springboot-mvc-4x
                    service-url: http://localhost:5402/
                enabled: true
                period: 1000
                url: http://localhost:9900
                auto-registration: true
                auto-deregistration: true
            routes:
                endpoints: auditevents, beans, caches, conditions, configprops, env, flyway, health, httpexchanges, info, integrationgraph, loggers, liquibase, metrics, mappings, quartz, scheduledtasks, sessions, shutdown, startup, threaddump, trace, heapdump, logfile, prometheus
    #
    # Ganti profile sesuai dengan database yang digunakan
    #
    profiles:
        #active: "db2"
        #active: "derby"
        #active: "h2"
        #active: "hsql"
        #active: "mariadb"
        active: "mysql"
        #active: "oracle"
        #active: "postgresql"
        #active: "sqlserver"                
#
# MANAGEMENT (SBADMIN)
#
management:
    health:
        key:
            enabled: true
        probes:
            enabled: true
    endpoints:
       web:
           base-path: /_/actuator
           enable:
               include: true
           exposure:
               include: '*'
    endpoint:
        health:
            enabled: true
            show-details: always
        startup:
            access: unrestricted
        shutdown:
            access: unrestricted

#
# LOGGING
#
logging:
    file:
        name: './logs/template-springboot-mvc-4x.log'
    pattern:
        console: '%d %p [%X{traceId}] %F\(%M:%L\) : %msg%n'
        file: '%d %p [%X{traceId}] %F\(%M:%L\) : %msg%n'
    level:
        org:
            hibernate: INFO
            springframework: INFO
            apache:
                fory: OFF
        redis:
            clients:
                jedis:
                    JedisFactory: OFF
        com:
            fasterxml:
                jackson:
                    dataformat:
                        xml: OFF
            zaxxer:
                hikari:
                    pool:
                        ProxyConnection: ERROR
        net:
            ideahut:
                springboot:
                    bean: DEBUG

#
# CONFIG
#
config:
    publicBaseUrl: ''
    logAllError: true
    binarySerializer: hessian_2
    autoStartScheduler: false
    messagePath: 'file:{user.dir}/extras/message/'
    reportPath: 'file:{user.dir}/extras/report/'

    #
    # LAUNCHER
    #
    launcher:
        waitAllProcess: true
        init:
            mapper: true
            validation: true
            endpoint: true
        log:
            initHandler: true
            beanInitialize: true
            beanConfigure: true
            beanShutdown: true
            version: true
            application: true
        configure:
            concurrency: 0
            beans:
                - net.ideahut.springboot.entity.EntityTrxManager
                - net.ideahut.springboot.sysparam.SysParamHandler
                - net.ideahut.springboot.audit.AuditHandler
    
    #
    # FILTER
    #
    filter:
        traceEnable: true
        resultTimeEnable: true
        resultTimeUnit: NANOSECONDS
        headers:
            Access-Control-Allow-Credentials: 'true'
            Access-Control-Allow-Origin: '*'
            Access-Control-Allow-Methods: '*'
            Access-Control-Max-Age: '3600'
            Access-Control-Allow-Headers: '*'
            Access-Control-Expose-Headers: '*'
    
    #
    # Model / Entity yang punya annotation @ForeignKeyEntity akan dieksekusi
    # Beberapa database tidak support "... on update (CASCADE/SET_NULL)"
    #
    foreignKey:
        enableExecution: true
        asyncExecution: true
        dropBeforeCreate: true
        onUpdateAction: true

    #
    # CRUD
    # 
    crud:
        enableApiService: false
        enablePermission: false
        alwaysUseNative: false
        defaultMaxLimit: 100
        infoEnabled: true
        bulkEnabled: true
        maxBulkSize: 0
        maxBulkLayer: 0

    #
    # AUDIT
    #
    audit:
        useMultiTable: true
        rejectNonAuditEntity: true
        properties:
            generate:
                table: true
            enable:
                audit: true
            table:
                prefix: _a_

    #
    # TASK
    #
    task:
        primary:
            threadNamePrefix: TASK-PRIMARY
            corePoolSize: 2
            maxPoolSize: 8
            waitForJobsToCompleteOnShutdown: true
        audit:
            threadNamePrefix: TASK-AUDIT
            corePoolSize: 2
            maxPoolSize: 8
            waitForJobsToCompleteOnShutdown: true
        rest:
            threadNamePrefix: TASK-REST
            corePoolSize: 16
            maxPoolSize: 1000
            waitForJobsToCompleteOnShutdown: true
        webAsync:
            threadNamePrefix: WEB-ASYNC
            corePoolSize: 8
            maxPoolSize: 100
            waitForJobsToCompleteOnShutdown: true

    #
    # REDIS
    #
    redis:
        primary:
            type: 0
            standalone:
                host: '<HOST>'
                port: '<PORT>'
                #password: '<PASSWORD>'
                database: 0
        access:
            type: 0
            standalone:
                host: '<HOST>'
                port: '<PORT>'
                database: 1
                
    #
    # ADMIN
    #
    admin:
        handler:
            configurationFile: 'file:{user.dir}/extras/admin/configuration.yaml'
            apiPath: /_/api
            webPath: /_/web
            webLocation: 'file:{user.dir}/extras/admin/web/'
            webEnabled: true
            storageKeyParam:
                prefix: ADMIN-HANDLER
                appIdEnabled: true
                encryptEnabled: true
        credential:
            useLocalMemory: false
            credentialFile: 'file:{user.dir}/extras/admin/credential.yaml'
            
            # LocalMemoryCredential
            checkInterval:
                unit: SECONDS
                value: 30

            # RedisMemoryCredential
            storageKeyParam:
                prefix: ADMIN-CREDENTIAL
                appIdEnabled: true
                encryptEnabled: true
        security:
            useBasicAuth: false

            # Basic Auth
            realm: Admin

            # Admin Auth
            enableRemoteHost: false
            enableUserAgent: false
            headerKey: Authorization

    #
    # API
    #
    api:
        handler:
            enableCrud: true
            enableSync: false
            enableConsumer: true
            configureThreads: 2
            cacheKeyParam:
                prefix: API-HANDLER
                appIdEnabled: true
                encryptEnabled: true
        service:
            apiName: TEMPLATE-MVC-4X
            cacheExpiry:
                timeUnit: MINUTES
                accessNull: 2
                accessObject: 5
                consumerNull: 2
                consumerObject: 10
            cacheKeyParam:
                prefix: API-SERVICE
                appIdEnabled: true
                encryptEnabled: true
        token:
            consumerTokenStorageIndex: 1
            useApiTokenInProcessor: true
            processorJwtParam:
                secret: 77ea06ac-808b-4399-895c-a546b033d533
                digest: SHA-256
                expiry:
                    unit: MINUTES
                    value: 60
            consumerJwtParam:
                secret: df7c7d71-ec05-4ad4-9b36-1580b1a6590f
                digest: SHA-256
                expiry:
                    unit: HOURS
                    value: 24
            ## toleransi waktu atas/bawah timestamp
            signatureTimeSpan:
                unit: SECONDS
                value: 60
    
    #
    # REST
    #
    rest:
        clientDestroyable: true
        enableExecutionTime: true
        enableRequestLimit: true
        defaultRestClient:
            # set false jika menggunakan proxy
            noProxy: true
            proxy:
                # DIRECT / HTTP / SOCKS
                type: DIRECT
                port:
                username:
                password:
                authorization:
            followRedirects: true
            timeout:
                timeUnit: SECONDS
                connect: 10
                call:
                read: 30
                write:
    
    #
    # CACHE         
    #
    cache:
        useLocalMemory: false
        
        # local memory
        expiryCheckInterval:
            unit: SECONDS
            value: 5
            
        # redis
        storageKeyParam:
            prefix: CACHE
            appIdEnabled: true
            encryptEnabled: true
            
        groups:
            -
                name: GROUP-01
                limit: 20
                expiry:
                    unit: SECONDS
                    value: 3600
                nullable: true
            -
                name: GROUP-02
                limit: -1
                expiry:
                    unit: SECONDS
                    value: 0
                nullable: false

    #
    # GRID
    #
    grid:
        useLocalMemory: false
        storageKeyParam:
            appIdEnabled: true
            encryptEnabled: true
        location: 'file:{user.dir}/extras/grid/**/*.json'
        #definition: 'file:{user.dir}/extras/grid/grid.def'
    
    #
    # MAIL
    #
    mail:
        host: 'smtp.gmail.com'
        port: 587
        username: '<USERNAME>'
        password: '<PASSWORD>'
        properties:
            mail.smtp.host: smtp.gmail.com
            mail.smtp.ssl.trust: smtp.gmail.com
            mail.smtp.port: 587
            mail.smtp.auth: true
            mail.smtp.starttls.enable: true
            mail.imap.ssl.enable: true
            mail.transport.protocol: smtp
            mail.debug: true
            mail.smtp.ssl.protocols: TLSv1.2

    #
    # KAFKA
    #
    kafka:
        kafkaEnabled: true
        configurationFile: 'file:{user.dir}/extras/kafka/localhost.yaml'
        deleteUnusedGroupAndTopic: true
        reloadEnabled: true
        broadcastEnabled: true
        broadcastTopic: 'template-springboot-mvc-4x'

    #
    # TRX MANAGER
    #
    trxManager:
        primary:
            datasource:
                # Type datasource bisa diubah-ubah, pilihan: HIKARI / AGROAL / DBCP / BASIC
                # Untuk JNDI bisa menambahkan 'jndiName' di type 'BASIC'
                type: HIKARI
                hikari:
                    connectionTimeout:
                        unit: SECONDS
                        value: 15
                    minimumIdle: 10
                    maximumPoolSize: 10
                    idleTimeout:
                        unit: SECONDS
                        value: 600
                    maxLifetime:
                        unit: SECONDS
                        value: 1800
                    poolName: PrimaryMainPool
                    enableVirtualThread: true
                agroal:
                    initialSize: 10
                    maxSize: 10
                    minSize: 10
                dbcp:
                    testWhileIdle: true
                    initialSize: 10
                    maxIdle: 10
                    maxTotal: 10
                    jmxName: 'PrimaryMainDataSource'
                basic:
                    #jndiName: 'TemplateSpringBootJNDI'
            settings:
                hibernate:
                    hbm2ddl:
                        auto: update
                    show_sql: true
                    generate_statistics: true
            useReflection: false
            entityPackages:
                - net.ideahut.springboot.api.entity
                - net.ideahut.springboot.job.entity
                - net.ideahut.springboot.message.entity
                - net.ideahut.springboot.sysparam.entity
                - net.ideahut.springboot.template.entity
            entityClasses:
                - net.ideahut.springboot.entity.replica.ReplicaInfo
                
                #
                # Aktifkan daftar entity di bawah pada saat jalan sebagai native image
                # Karena package scanning tidak berfungsi di native image.
                #
                
                # API
                #- net.ideahut.springboot.api.entity.ApiConnect
                #- net.ideahut.springboot.api.entity.ApiConnectRole
                #- net.ideahut.springboot.api.entity.ApiCrud
                #- net.ideahut.springboot.api.entity.ApiCrudExclude
                #- net.ideahut.springboot.api.entity.ApiCrudField
                #- net.ideahut.springboot.api.entity.ApiItemCrud
                #- net.ideahut.springboot.api.entity.ApiItemRequest
                #- net.ideahut.springboot.api.entity.ApiProvider
                #- net.ideahut.springboot.api.entity.ApiProviderConfig
                #- net.ideahut.springboot.api.entity.ApiProviderCrud
                #- net.ideahut.springboot.api.entity.ApiProviderCrudAction
                #- net.ideahut.springboot.api.entity.ApiProviderCrudFilter
                #- net.ideahut.springboot.api.entity.ApiProviderHost
                #- net.ideahut.springboot.api.entity.ApiProviderRequest
                #- net.ideahut.springboot.api.entity.ApiRole
                #- net.ideahut.springboot.api.entity.ApiRoleCrud
                #- net.ideahut.springboot.api.entity.ApiRoleCrudAction
                #- net.ideahut.springboot.api.entity.ApiRoleCrudFilter
                #- net.ideahut.springboot.api.entity.ApiRoleRequest
                
                # JOB
                #- net.ideahut.springboot.job.entity.JobGroup
                #- net.ideahut.springboot.job.entity.JobInstance
                #- net.ideahut.springboot.job.entity.JobTrigger
                #- net.ideahut.springboot.job.entity.JobTriggerConfig
                #- net.ideahut.springboot.job.entity.JobType
                #- net.ideahut.springboot.job.entity.JobTypeParam
                
                # MESSAGE
                #- net.ideahut.springboot.message.entity.Language
                #- net.ideahut.springboot.message.entity.Message
                
                # SYSPARAM
                #- net.ideahut.springboot.sysparam.entity.SysParam
                
                # APPLICATION
                #- net.ideahut.springboot.template.entity.AutoGenLongIdHardDel
                #- net.ideahut.springboot.template.entity.AutoGenStrIdHardDel
                #- net.ideahut.springboot.template.entity.AutoGenStrIdSoftDel
                #- net.ideahut.springboot.template.entity.CompositeHardDel
                #- net.ideahut.springboot.template.entity.CompositeSoftDel
                #- net.ideahut.springboot.template.entity.EmbeddedHardDel
                #- net.ideahut.springboot.template.entity.EmbeddedSoftDel
                #- net.ideahut.springboot.template.entity.EmbeddedWithoutAttribute
                #- net.ideahut.springboot.template.entity.Information
                #- net.ideahut.springboot.template.entity.InformationLink
                #- net.ideahut.springboot.template.entity.IntegerIdWithBytes
                #- net.ideahut.springboot.template.entity.LongIdJoinComposite
                #- net.ideahut.springboot.template.entity.LongIdJoinEmbedded
                #- net.ideahut.springboot.template.entity.ManualGenStrIdSoftDel
                #- net.ideahut.springboot.template.entity.Menu
                #- net.ideahut.springboot.template.entity.MenuRole
                #- net.ideahut.springboot.template.entity.Role
                #- net.ideahut.springboot.template.entity.User
                #- net.ideahut.springboot.template.entity.UserDetail
                #- net.ideahut.springboot.template.entity.UserFavorite
                
            audit:
                id: template_springboot_mvc_1
                datasource:
                    type: HIKARI
                    hikari:
                        poolName: PrimaryAuditPool
                        enableVirtualThread: true
                settings:
                    hibernate:
                        show_sql: true
                        generate_statistics: true 

        secondary:
            datasource:
                type: HIKARI
                hikari:
                    connectionTimeout:
                        unit: SECONDS
                        value: 15
                    minimumIdle: 10
                    maximumPoolSize: 10
                    idleTimeout:
                        unit: SECONDS
                        value: 600
                    maxLifetime:
                        unit: SECONDS
                        value: 1800
                    poolName: SecondaryMainPool
                    enableVirtualThread: true
            settings:
                hibernate:
                    hbm2ddl:
                        auto: update
                    show_sql: true
                    generate_statistics: true
            useReflection: false
            entityClasses:
                - net.ideahut.springboot.template.entity.Information
                - net.ideahut.springboot.template.entity.CompositeHardDel
            audit:
                id: template_springboot_mvc_2
                datasource:
                    type: HIKARI
                    hikari:
                        poolName: SecondaryAuditPool
                        enableVirtualThread: true
                settings:
                    hibernate:
                        show_sql: true
                        generate_statistics: true
